### ISSUE TITLE
Pause on steam overlay functionality

### ISSUE THREAD

**Issue by therealpaulgg** [popsUlfr/SDH-PauseGames#3]
Hi,

I was wondering, as an extension of the 'pause on focus loss', would it be possible to have a feature that when the STEAM button is pressed and the overlay is brought up, the game is suspended? The game would also be paused when browsing the library, or friends tab, etc.

The main idea behind this is there are several games (singleplayer, emulated) that won't automatically pause themselves. It would be desirable to have them auto-pause and unpause when pressing the STEAM button, similar to pressing the Home button on the nintendo switch.

I don't have any experience developing decky plugins but do know JS/TS/react and I'd be happy to contribute to make this happen...was looking [here](https://github.com/popsUlfr/SDH-PauseGames/blob/78201913795b909a59db179c1e3b1877393075d4/src/backend.ts#L324). Specifically the steam overlay is mentioned but I'm unsure if this would even be possible to accomplish or not.

**Comment by therealpaulgg** [comment]
If you are interested, I implemented this feature on a separate fork.
https://github.com/therealpaulgg/SDH-PauseGames/commit/2ff05251139c363a082b6e39a174a1f9ad57c522

**Comment by popsUlfr** [comment]
In my first iteration for the "Pause on focus loss" feature I experimented with this but there are edge cases that would have made it annoying or potentially break some use cases. Like using a STEAM + other button combination to take a screenshot, magnify the screen etc where you don't want to stop the application. Or a launcher downloading game assets, steamworks subscriptions processing additional content, any instance you just want to look something up or change the controller layout without outright wanting to put the application to sleep. Potential Steam Overlay and Quick Access Menu shenanigans.

As a separate feature it has its chances though, thank you for looking into this. It might make sense to put it as a sub-option to the "Pause on focus loss" feature since it would be a more "aggressive" version of it ?

If you feel like you have something that works or a draft don't hesitate to submit a pull request I'll try to test it on my end :)

**Comment by therealpaulgg** [comment]
https://github.com/popsUlfr/SDH-PauseGames/pull/4
